### ISSUE TITLE
Chýba nový riadok na vstupe

### ISSUE THREAD

**Issue by xdudakm** [FedorViest/opp_prpr2024#1]
Vyzerá to, ako by na konci vstupu nedávalo nový riadok (enter). Keď spustím uvedený program ručne, zoberie to vstup 
```
v 1
h

```
ale na testeri to padne s výstupom `ERROR | Test 'Test 1: Unsuccessful file opening': Got Timeout`, pretože to neprešlo cez getchar(). 

```
#include <stdio.h>
int main() {
    getchar();
    getchar(); //newline or space
    getchar();
    getchar(); //newline
    printf("V1: Neotvorene txt subory.\n");
    getchar();
    getchar(); //newline
    printf("H: Neotvoreny subor.\n");
    return 0;
}
```

input.yaml:
```
tests:
  - name: "Test 1: Unsuccessful file opening"
    points: 2
    sequence:
      - in : "v 1"
      - out: "V1: Neotvorene txt subory."
      - out: ""
  - name: "Test 2: h"
    points: 2
    sequence:
      - in: "h"
      - out: "H: Neotvoreny subor."
      - out: ""
```

**Comment by WhenGrill** [comment]
Tester funguje na princípe, že **každý test == nové spustenie programu**. Čiastková kontrola inputov nie je možná pokiaľ sa program neukončí.

Tester v `input.yaml` pri parametri `out:` už očakáva znak nového riadku `\n` a pre to nie je potrebné dávať samostaný prázdny `out: ""` parameter.


V tvojom prípade by test vyzeral nasledovne:

```yaml
tests:
  - name: "Test 1: Unsuccessful file opening"
    points: 2
    sequence:
      - in : "v 1"
      - out: "V1: Neotvorene txt subory."
      - in: "a"  # Ockavas getchar, random input 
      - out: "H: Neotvoreny subor."
```

Odskúšané, tester dáva očakávaný výsledok. **Vďaka za issue <3**
